# Site wide configuration

title: "Denys Antipenko"
description: "Character Animator. Cinematic Artist."
logo: 120x120.gif
teaser: 400x250.gif
locale: en_US
url: "http://umych.com"
feed:
  path: atom.xml

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed


# Site owner
owner:
  name: "Denys Antipenko"
  web: "http://umych.com"
  twitter: "umych_sir"
  bio: "Just another boring character animator."
  avatar: "bio-photo.jpg" # 160x160 px image for author byline
  # disqus-shortname:


include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
  - Dockerfile
  - docker-compose.yml
  - .nvmrc
  - Gemfile.lock
  - package-lock.json
  - start.sh
  - .dockerignore
